import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, ArrowUpRight, BrainCircuit, Clock3, FileText, Gauge, MapPinned, Menu, Send, ShieldCheck, Sparkles, TrainFront, X } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from './api/client'
import ShapWaterfall from './components/ShapWaterfall'
import RouteRiskMap from './components/RouteRiskMap'

const fallback = { health: { on_time_percentage: 87.4, active_anomalies: 7, average_delay_hours: 3.8, high_risk_shipments: 24, shipments_monitored: 1842 }, routes: [], yards: [], alerts: [], models: { feature_importance: [] }, leaderUpdate: { period: 'Sep 23 - Sep 29, 2026', headline: 'Network reliability held steady while two Midwest yards experienced elevated dwell.', insights: [], recommended_actions: [] } }
const nav = [{ label: 'Network overview', icon: Activity }, { label: 'ETA predictor', icon: Clock3 }, { label: 'Routes & yards', icon: MapPinned }, { label: 'Anomaly center', icon: AlertTriangle }, { label: 'Leader update', icon: FileText }, { label: 'Model intelligence', icon: BrainCircuit }]

function Metric({ label, value, detail, icon: Icon, tone = 'teal' }) { return <div className="metric"><div className={`metric-icon ${tone}`}><Icon size={18} /></div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></div> }
function RiskPill({ risk }) { return <span className={`risk ${risk}`}>{risk}</span> }

function App() {
  const [data, setData] = useState(fallback)
  const [active, setActive] = useState('Network overview')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [predicting, setPredicting] = useState(false)
  const [prediction, setPrediction] = useState(null)
  const [form, setForm] = useState({ origin_yard: 'Alliance', destination_yard: 'Chicago', distance_miles: 780, interchanges: 1, priority: 'Standard', train_priority: 2, origin_delay_rate: 0.08, destination_delay_rate: 0.12 })

  useEffect(() => { Promise.all([api.health(), api.routes(), api.yards(), api.alerts(), api.models(), api.leaderUpdate()]).then(([health, routes, yards, alerts, models, leaderUpdate]) => setData({ health, routes, yards, alerts, models, leaderUpdate })).catch(() => {}) }, [])
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setPredicting(true); try { setPrediction(await api.predict({ ...form, distance_miles: Number(form.distance_miles), interchanges: Number(form.interchanges), train_priority: Number(form.train_priority) })) } catch { setPrediction({ predicted_delay_hours: 4.8, on_time_probability: 0.7, risk_level: 'medium', contributing_factors: [{ feature: 'Interchanges', impact: 0.72 }], model_version: 'offline preview' }) } finally { setPredicting(false) } }
  const h = data.health
  const chartData = data.routes[0]?.trend?.map((delay, index) => ({ day: `Sep ${23 + index}`, delay })) || [{ day: 'Mon', delay: 3.2 }, { day: 'Tue', delay: 4 }, { day: 'Wed', delay: 3.7 }, { day: 'Thu', delay: 5.1 }, { day: 'Fri', delay: 5.8 }, { day: 'Sat', delay: 4.9 }, { day: 'Sun', delay: 5.8 }]

  return <div className="app-shell">
    <aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark"><TrainFront size={21} /></div><div><strong>RAILPULSE</strong><span>NETWORK INTELLIGENCE</span></div><button className="close-menu" onClick={() => setMobileOpen(false)}><X size={19} /></button></div><div className="workspace"><span className="eyebrow">OPERATIONS CENTER</span><div className="workspace-row"><span className="status-dot" /> Live network</div></div><nav>{nav.map(({ label, icon: Icon }) => <button className={active === label ? 'nav-item active' : 'nav-item'} key={label} onClick={() => { setActive(label); setMobileOpen(false) }}><Icon size={17} />{label}{label === 'ETA predictor' && <span className="nav-badge">AI</span>}</button>)}</nav><div className="sidebar-footer"><div className="pulse-line"><span /><span /><span /><span /><span /><span /><span /></div><p>Prediction service<br /><strong>operational</strong></p><small>Model v1.0.4 &middot; Updated 8m ago</small></div></aside>
    <main><header><button className="menu-button" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><div><span className="eyebrow">WEDNESDAY, SEPTEMBER 30, 2026</span><h1>{active}</h1></div><div className="header-actions"><span className="live-label"><span className="status-dot" /> System live</span><button className="avatar">JD</button></div></header>
      <div className="content">
        {active === 'Network overview' && <>
          <section className="hero-row"><div><p className="kicker"><Sparkles size={14} /> INTELLIGENCE BRIEF</p><h2>See the network<br /><em>before it moves.</em></h2><p className="lede">Real-time signals across 1,842 active shipments, distilled into the decisions that keep freight moving.</p></div><div className="brief-card"><div className="brief-top"><span>WEEKLY SIGNAL</span><ArrowUpRight size={17} /></div><strong>Reliability is up <b>2.1%</b></strong><p>Network on-time performance improved week over week. Midwest yards remain the focus area.</p><div className="brief-bar"><span /></div></div></section>
          <section className="metrics"><Metric label="On-time performance" value={`${h.on_time_percentage}%`} detail="↑ 2.1% vs last week" icon={Gauge} /><Metric label="Average delay" value={`${h.average_delay_hours}h`} detail="↓ 0.4h vs last week" icon={Clock3} tone="amber" /><Metric label="Active anomalies" value={h.active_anomalies} detail="3 require attention" icon={AlertTriangle} tone="coral" /><Metric label="High-risk shipments" value={h.high_risk_shipments} detail="1.3% of network" icon={ShieldCheck} tone="blue" /></section>
          <section className="grid-main"><div className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">CORRIDOR PERFORMANCE</span><h3>Average delay by day</h3></div><span className="select-like">Last 7 days <span>⌄</span></span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="delayFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00a99d" stopOpacity={0.28}/><stop offset="100%" stopColor="#00a99d" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#85929a', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#85929a', fontSize: 11 }} tickFormatter={(v) => `${v}h`} /><Tooltip contentStyle={{ border: '1px solid #dce5e3', borderRadius: 4, fontSize: 12 }} /><Area type="monotone" dataKey="delay" stroke="#00a99d" strokeWidth={2.5} fill="url(#delayFill)" /></AreaChart></ResponsiveContainer></div></div><div className="panel alerts-panel"><div className="panel-head"><div><span className="eyebrow">ATTENTION REQUIRED</span><h3>Active alerts</h3></div><span className="count-badge">{data.alerts.length || 3}</span></div><div className="alerts-list">{(data.alerts.length ? data.alerts : [{ type: 'Dwell spike', severity: 'high', yard: 'Chicago', message: 'Average dwell is 41% above the 30-day baseline.', time: '12 min ago' }, { type: 'Scan gap', severity: 'medium', yard: 'Memphis', message: '18 railcars have not reported a scan in 9.4 hours.', time: '34 min ago' }, { type: 'Corridor congestion', severity: 'low', yard: 'Alliance', message: 'Eastbound interchange queue is trending above normal.', time: '1 hr ago' }]).map(alert => <div className="alert" key={alert.type}><div className={`alert-icon ${alert.severity}`}><AlertTriangle size={14} /></div><div><div className="alert-title"><strong>{alert.type}</strong><span>{alert.yard}</span></div><p>{alert.message}</p><small>{alert.time}</small></div></div>)}</div></div></section>
          <section className="grid-bottom"><div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">ROUTE RISK INDEX</span><h3>Corridors to watch</h3></div><button className="text-button" onClick={() => setActive('Routes & yards')}>View analysis <ArrowUpRight size={14} /></button></div><div className="table-scroll"><table><thead><tr><th>Corridor</th><th>Avg delay</th><th>Risk</th><th>7-day trend</th></tr></thead><tbody>{(data.routes.length ? data.routes : [{ route: 'Alliance -> Chicago', delay: 5.8, risk: .31, trend: chartData.map(x => x.delay) }, { route: 'Omaha -> Memphis', delay: 7.4, risk: .46, trend: [5, 6, 7, 7, 8, 7, 7] }, { route: 'Fort Worth -> Kansas City', delay: 3.1, risk: .18, trend: [2, 3, 2, 4, 3, 3, 3] }]).map(route => <tr key={route.route}><td><strong>{route.route}</strong><small>7 segments &middot; 1 interchange</small></td><td><strong>{route.delay}h</strong></td><td><RiskPill risk={route.risk > .4 ? 'high' : route.risk > .2 ? 'medium' : 'low'} /></td><td><div className="mini-bars">{route.trend.map((v, i) => <i key={i} style={{ height: `${Math.max(25, v / 8 * 100)}%` }} />)}</div></td></tr>)}</tbody></table></div></div></section>
        </>}
        {active === 'ETA predictor' && <section className="predict-page"><div className="page-intro"><span className="eyebrow">PREDICTIVE OPERATIONS</span><h2>Calculate shipment risk.</h2><p>Estimate arrival delay and understand what is driving the prediction before you commit resources.</p></div><div className="predict-layout"><form className="panel predict-form" onSubmit={submit}><div className="form-head"><BrainCircuit size={19} /><div><h3>Shipment profile</h3><p>Use current route and operating conditions.</p></div></div><div className="form-grid"><label>Origin yard<select name="origin_yard" value={form.origin_yard} onChange={update}><option>Alliance</option><option>Fort Worth</option><option>Omaha</option><option>Kansas City</option></select></label><label>Destination yard<select name="destination_yard" value={form.destination_yard} onChange={update}><option>Chicago</option><option>Memphis</option><option>Kansas City</option><option>Fort Worth</option></select></label><label>Distance (miles)<input type="number" name="distance_miles" value={form.distance_miles} onChange={update} /></label><label>Interchanges<input type="number" name="interchanges" value={form.interchanges} onChange={update} min="0" max="4" /></label><label>Service priority<select name="priority" value={form.priority} onChange={update}><option>Standard</option><option>Expedited</option></select></label><label>Train priority<select name="train_priority" value={form.train_priority} onChange={update}><option value="1">1 - Critical</option><option value="2">2 - Standard</option><option value="3">3 - Economy</option></select></label></div><button className="primary-button" disabled={predicting}>{predicting ? 'Running model...' : 'Run ETA prediction'} <Send size={16} /></button></form><div className={prediction ? 'panel result-card revealed' : 'panel result-card'}>{prediction ? <><span className="eyebrow">PREDICTION RESULT</span><div className="result-number">{prediction.predicted_delay_hours}<small>hours predicted delay</small></div><div className="result-line"><span>On-time probability</span><strong>{Math.round(prediction.on_time_probability * 100)}%</strong></div><div className="probability"><span style={{ width: `${prediction.on_time_probability * 100}%` }} /></div><div className="result-line"><span>Risk classification</span><RiskPill risk={prediction.risk_level} /></div><div className="factors"><h4>SHAP contribution waterfall</h4><ShapWaterfall factors={prediction.contributing_factors} /></div><small className="model-note">Served by {prediction.model_version}</small></> : <div className="empty-result"><div><Sparkles size={27} /></div><h3>Ready when you are.</h3><p>Enter shipment details to get a live ETA estimate and explainable risk factors.</p></div>}</div></div></section>}
        {active === 'Routes & yards' && <section className="data-page"><div className="page-intro"><span className="eyebrow">NETWORK TOPOLOGY</span><h2>Where the network breathes.</h2><p>Compare corridor reliability and yard throughput to find the next constraint.</p></div><div className="panel heatmap-panel"><div className="panel-head"><div><span className="eyebrow">ROUTE RISK HEATMAP</span><h3>Corridor exposure at a glance</h3></div></div><RouteRiskMap routes={data.routes} /></div><div className="data-grid"><div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">ROUTE RISK INDEX</span><h3>All monitored corridors</h3></div></div><table><thead><tr><th>Corridor</th><th>Delay</th><th>Risk score</th></tr></thead><tbody>{data.routes.map(r => <tr key={r.route}><td><strong>{r.route}</strong></td><td>{r.delay}h</td><td><RiskPill risk={r.risk > .4 ? 'high' : r.risk > .2 ? 'medium' : 'low'} /></td></tr>)}</tbody></table></div><div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">YARD PERFORMANCE</span><h3>Throughput & dwell</h3></div></div><table><thead><tr><th>Yard</th><th>Throughput</th><th>Dwell</th></tr></thead><tbody>{data.yards.map(y => <tr key={y.id}><td><strong>{y.id}</strong><small>{y.region}</small></td><td>{y.throughput}<small>cars / day</small></td><td>{y.dwell}h</td></tr>)}</tbody></table></div></div></section>}
        {active === 'Anomaly center' && <section className="data-page"><div className="page-intro"><span className="eyebrow">OPERATIONAL MONITORING</span><h2>Find the outliers early.</h2><p>Every alert is scored against the learned operating baseline so teams can focus on the exceptions that matter.</p></div><div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">ANOMALY QUEUE</span><h3>Flagged operating patterns</h3></div><span className="count-badge">{data.alerts.length || 3} active</span></div><table><thead><tr><th>Signal</th><th>Location</th><th>Severity</th><th>Explanation</th><th>Detected</th></tr></thead><tbody>{(data.alerts.length ? data.alerts : [{ type: 'Dwell spike', yard: 'Chicago', severity: 'high', message: 'Average dwell is 41% above the 30-day baseline.', time: '12 min ago' }, { type: 'Scan gap', yard: 'Memphis', severity: 'medium', message: '18 railcars have not reported a scan in 9.4 hours.', time: '34 min ago' }]).map(alert => <tr key={`${alert.type}-${alert.yard}`}><td><strong>{alert.type}</strong></td><td>{alert.yard}</td><td><RiskPill risk={alert.severity} /></td><td>{alert.message}</td><td>{alert.time}</td></tr>)}</tbody></table></div></section>}
        {active === 'Leader update' && <section className="data-page"><div className="page-intro"><span className="eyebrow">EXECUTIVE BRIEFING</span><h2>One clear readout.</h2><p>Weekly network intelligence formatted for a leader conversation.</p></div><div className="briefing-grid"><div className="panel briefing-hero"><span className="eyebrow">{data.leaderUpdate.period}</span><h3>{data.leaderUpdate.headline}</h3><div className="brief-bar"><span /></div></div><div className="panel performance"><span className="eyebrow">KEY INSIGHTS</span>{data.leaderUpdate.insights.map((insight, index) => <div className="insight" key={insight}><b>0{index + 1}</b><span>{insight}</span></div>)}</div><div className="panel performance"><span className="eyebrow">RECOMMENDED ACTIONS</span>{data.leaderUpdate.recommended_actions.map(action => <div className="insight action" key={action}><ShieldCheck size={15} /><span>{action}</span></div>)}</div></div></section>}
        {active === 'Model intelligence' && <section className="data-page"><div className="page-intro"><span className="eyebrow">MODEL CARD</span><h2>Trust the signal.</h2><p>Transparent model performance and the features shaping network predictions.</p></div><div className="model-grid"><div className="panel performance"><span className="eyebrow">VALIDATION PERFORMANCE</span><h3>Models in production</h3>{(data.models.models || [{ name: 'XGBoost ETA Regressor', rmse_hours: 2.14, r2: .78 }, { name: 'On-time Classifier', auc: .86, f1: .79 }, { name: 'Isolation Forest', precision: .71, recall: .68 }]).map(m => <div className="model-row" key={m.name}><div><strong>{m.name}</strong><small>{m.type || 'production model'}</small></div><b>{m.rmse_hours ? `${m.rmse_hours}h RMSE` : m.auc ? `${Math.round(m.auc * 100)}% AUC` : `${Math.round(m.precision * 100)}% precision`}</b></div>)}</div><div className="panel performance"><span className="eyebrow">EXPLAINABILITY</span><h3>Top risk signals</h3>{(data.models.feature_importance || []).map(f => <div className="importance" key={f.feature}><div><span>{f.feature.replaceAll('_', ' ')}</span><b>{Math.round(f.importance * 100)}%</b></div><div className="importance-bar"><span style={{ width: `${f.importance * 100 / .3}%` }} /></div></div>)}</div></div></section>}
      </div><footer><span>RAILPULSE AI <b>v1.0.4</b></span><span>Data refreshes every 5 minutes <i className="status-dot" /></span></footer>
    </main>
  </div>
}
export default App
